"""add recipes table and user relationship

Revision ID: 1ccbc509252a
Revises: edceb17860ae
Create Date: 2026-04-22 20:56:01.434890

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1ccbc509252a'
down_revision = 'edceb17860ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('image', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ready_in_minutes', sa.Integer(), nullable=False),
    sa.Column('servings', sa.Integer(), nullable=False),
    sa.Column('source_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('vegetarian', sa.Boolean(), nullable=False),
    sa.Column('vegan', sa.Boolean(), nullable=False),
    sa.Column('gluten_free', sa.Boolean(), nullable=False),
    sa.Column('dairy_free', sa.Boolean(), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cuisines', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('diets', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('analyzed_instructions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipes_recipe_id'), 'recipes', ['recipe_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recipes_recipe_id'), table_name='recipes')
    op.drop_table('recipes')
    # ### end Alembic commands ###