"""add recipes table

Revision ID: 1f091fb003a0
Revises: 1ccbc509252a
Create Date: 2026-04-22 21:01:39.009093

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '1f091fb003a0'
down_revision = '1ccbc509252a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###