"""add pantry items table

Revision ID: edceb17860ae
Revises: b1a350e6bdec
Create Date: 2026-04-13 18:59:21.908209

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'edceb17860ae'
down_revision = 'b1a350e6bdec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pantry_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('aisle', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pantry_items_ingredient_id'), 'pantry_items', ['ingredient_id'], unique=False)
    op.create_index(op.f('ix_pantry_items_name'), 'pantry_items', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pantry_items_name'), table_name='pantry_items')
    op.drop_index(op.f('ix_pantry_items_ingredient_id'), table_name='pantry_items')
    op.drop_table('pantry_items')
    # ### end Alembic commands ###